### ISSUE TITLE
Low resolution images shared

### ISSUE THREAD

**Issue by AlanBell** [stuartlangridge/pubphoto#4]
The image is scaled to fit in a 500px box https://github.com/stuartlangridge/pubphoto/blob/master/index.html#L963 which is probably something that could be configured somewhere, or consider an option on sending to send the full resolution image.

**Comment by stuartlangridge** [comment]
I don't think so. I understand the thought process, but Soonsnap's overriding goal, which takes precedence over everything else, is making the transaction as quick and unobtrusive as possible. We shrink the image to minimise the amount of time taken for the transfer, and to reduce the bandwidth that has to be shipped through the back end, and the screens are all as basic as is possible to avoid confusion. I don't think that the benefits from sending a larger image (that you get a higher-quality image) outweigh the deficits (the sending screen is mildly more confusing; transfer takes longer), which is why we shrink the image.

**Comment by AlanBell** [comment]
That is a reasonable thought process, however it was surprising to me that it did it, and took me some time to figure out where the loss of resolution was happening. Maybe the behavior could be mentioned in the documentation somewhere.

**Comment by stuartlangridge** [comment]
I have updated https://www.kryogenix.org/days/2014/05/13/some-thoughts-on-soonsnap-and-little-big-details/ to explicitly explain why the 500px restriction and how to remove it (thank you for the above, which made that easy) and linked to it from the README for future reference.
